### ISSUE TITLE
'could not serialize access due to concurrent update' with Postgre storage

### ISSUE THREAD

**Issue by Frazi1** [face-it/Hangfire.Tags#35]
First of all, thank you for developing this package. It is an almost perfect library to meet our business needs. Unfortunately, I encountered concurrency update issues happening at job creation time.

## My config:
PostgreSQL 10 (running locally on my dev machine)
Hangfire 1.7.19
Hangfire.Postgre 1.8.1
Hangfire.Tags.PostgreSql 1.7.1

## Exception
Here is the exception:
```c#

Hangfire.BackgroundJobClientException: Background job creation failed. See inner exception for details.
 ---> Npgsql.PostgresException (0x80004005): 40001: could not serialize access due to concurrent update
   at Npgsql.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|194_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader) in /_/Dapper/SqlMapper.cs:line 2822
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 572
   at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 443
   at Hangfire.PostgreSql.PostgreSqlWriteOnlyTransaction.<>c__DisplayClass18_0.<AddToSet>b__0(NpgsqlConnection con)
   at Hangfire.PostgreSql.PostgreSqlWriteOnlyTransaction.Commit()
   at Hangfire.Tags.Storage.TagsStorage.AddTags(String jobid, IEnumerable`1 tags)
   at Hangfire.Tags.HangfireExtensions.AddTags(String jobid, String[] tags)
   at Hangfire.Tags.States.CreateJobFilter.OnCreated(CreatedContext filterContext)
   at Hangfire.Client.BackgroundJobFactory.InvokeOnCreated(Tuple`2 x)
   at Hangfire.Profiling.ProfilerExtensions.InvokeAction[TInstance](InstanceAction`1 tuple)
   at Hangfire.Profiling.EmptyProfiler.InvokeMeasured[TInstance,TResult](TInstance instance, Func`2 action, String message)
   at Hangfire.Profiling.ProfilerExtensions.InvokeMeasured[TInstance](IProfiler profiler, TInstance instance, Action`1 action, String message)
   at Hangfire.Client.BackgroundJobFactory.InvokeClientFilter(IClientFilter filter, CreatingContext preContext, Func`1 continuation)
   at Hangfire.Client.BackgroundJobFactory.InvokeClientFilter(IClientFilter filter, CreatingContext preContext, Func`1 continuation)
   at Hangfire.Client.BackgroundJobFactory.InvokeClientFilter(IClientFilter filter, CreatingContext preContext, Func`1 continuation)
   at Hangfire.Client.BackgroundJobFactory.InvokeClientFilter(IClientFilter filter, CreatingContext preContext, Func`1 continuation)
   at Hangfire.Client.BackgroundJobFactory.InvokeClientFilter(IClientFilter filter, CreatingContext preContext, Func`1 continuation)
   at Hangfire.Client.BackgroundJobFactory.Create(CreateContext context)
   at Hangfire.BackgroundJobClient.Create(Job job, IState state)
  Exception data:
    Severity: ERROR
    SqlState: 40001
    MessageText: could not serialize access due to concurrent update
    File: nodeModifyTable.c
    Line: 1012
    Routine: ExecUpdate
   --- End of inner exception stack trace ---
   at Hangfire.BackgroundJobClient.Create(Job job, IState state)
   at LINE REMOVED HERE
```

## My use case:
The tags I use:
```c#
public class MyJobs
{
    [Tag("MyJobOperation", "{0}", "{1}", "relatedObject-{2}")]
    Task RunMyJobAsync(
      SomeEnum someEnum, //enum (about 10 values)
      string someJobType someJobType, //job type string (we can have about 10 unique values here)
      int relatedObjectId //An ID from our database
    );
}
```

Then, I have several recurring jobs that are responsible for creating `RunMyJobAsync` jobs for different `relatedObjectId`s. The recurring jobs can be run in parallel.

Here is the pseudo-code:
```c#
//Recurring job 1:

var someEnum = SomeEnum.Value1;
var someJobType = "MyFirstJobType";

for(int i=1, i<1000;i++)
{
    BackgroundJob.Enqueue<MyJobs>(a=>a.RunMyJob(someEnum, someJobType, i));
}

//Recurring job 2: running at the same time as Recurring job 1
var someEnum2 = SomeEnum.Value2; //The difference is here
var someJobType = "MyFirstJobType";

for(int i=1, i<1000;i++)
{
    BackgroundJob.Enqueue<MyJobs>(a=>a.RunMyJob(someEnum2, someJobType, i));
}
```

## Reasons?

I think it makes sense that I get a concurrency update error here due to the fact the Hangfire.Postgre uses `RepetableRead` isolation level for its transactions. I check [postgresql docs](https://www.postgresql.org/docs/9.1/transaction-iso.html) (1.3.2.2. Repeatable Read Isolation Level section), and here what it says:
> Applications using this level must be prepared to retry transactions due to serialization failures.

I could potentially add a try-catch in my code to get it resolved, but it does not look like the best way to do it.

I think, that Hangfire.Tags should provide some kind of a retry strategy to deal with concurrency updates. Neither it provides one now, nor it allows to plugin a custom retry strategy. There is a public interface `ITagsStorage`, but there is no chance to provide a custom implementation for that because everywhere `TagsStorage` class is used directly with a `new` keyword.

I would be happy if we could include a retry strategy directly into `TagsStorage.AddTags` method, or at least give an opportunity to provide custom `ITagsStorage` implementation so that I could implement a retry strategy myself.

Any ideas about how to better fix my issue are really appreciated. Thanks!

**Comment by erwin-faceit** [comment]
This is related, and apparently solved in Hangfire.PostgreSql itself: https://github.com/frankhommers/Hangfire.PostgreSql/pull/169. I'll update Hangfire.Tags.PostgreSql to use the updated version.

**Comment by Frazi1** [comment]
## Issue still exists
> This is related, and apparently solved in Hangfire.PostgreSql itself: [frankhommers/Hangfire.PostgreSql#169](https://github.com/frankhommers/Hangfire.PostgreSql/pull/169). I'll update Hangfire.Tags.PostgreSql to use the updated version.

Hi @erwin-faceit. The pull request in Hangfire.Postgre you linked resolved a similar issue, but in a completely different scenario. It fixes a concurrency error when a worker tries to claim a Hangfire job. However, Hangfire.Tags uses `IWriteOnlyTransaction` interface (or something similar) to store tags. These 2 things are completely unrelated in Hangfire.Postgre implementation.

Also, when I encountered this issue, I was already using the latest Hangfire.Postgre version (1.8.1).

I ask you that you reopen this issue because it still exist.

## Repro steps
I tried to reproduce it locally, but it never crashed. However, it crashes quite often on our production. I had to actually copy-paste `CreateFilter` class from Hangfire.Tags and implement a retry-policy on my own.

I'll try to build an environment to reproduce it. I still hope the bug is fixed at Hangfire.Tags.

**Comment by erwin-faceit** [comment]
Can you create a pull request with your Retry policy?

**Comment by Frazi1** [comment]
Sorry for being so slow building the environment to reproduce the issue.

I can definitely work on providing a pull request. I'll try to get started on the weekend.

**Comment by erwin-faceit** [comment]
No problem, if it's a simple class change, you can also just post it here, and I'll add it.

**Comment by Frazi1** [comment]
Finally, I managed to reproduce the issue.

## Environment
1. Laptop, Intel Core I5-3230m (2 cores + hyperthreading = 4 cores in total), 8 GB memory
2. Docker + postgres 13 (latest)
3. .NET Core 3.1 + AspNetCore 3

I'm not sure if my cpu is important here. Firstly, I tried reproducing it on another machine that has an I7-10700K with 16 cores. The source code was a little bit different, so I'm not sure.

Anyway, it fails steadily with the following repro steps on my current laptop. 

## Steps to reproduce
1. Checkout https://github.com/Frazi1/Hangfire.Tags.Postgres.ConcurrencyIssues repo
2. Setup postgres instance. I used the latest PostgreSql instance from docker.
    ```
    docker pull postgres
    docker run --name postgres-hangfire -e POSTGRES_PASSWORD=test -p 5432:5432 -d postgres
    ```
3. Create a fresh hangfire db
4. Go into `appsettings.Development.json` and adjust `HangfirePostgres` connection string to point at your local db
5. `dotnet run`
6. Open https://localhost:5001/hangfire
7. Wait a little bit

## Actual result:
After some time, jobs will start failing and will appear under `Retries` page on the dashboard. 
![image](https://user-images.githubusercontent.com/14334350/110187940-21299980-7e2b-11eb-928e-ad0454565a7b.png)
![image](https://user-images.githubusercontent.com/14334350/110187976-3a324a80-7e2b-11eb-9e31-0ecb61ca8cf1.png)

## Fixes
I'll try to get started working on the fix this weekend.

It may not be a simple class change since the retry policy is going to be storage-specific. We'll have to build a generic interface for the retry policy and make an implementation for Postgres. I'm not sure if a similar issue exists for other storages, but we can try it out later, I think.

Also, I'm not sure how many retries we want to have in there. I have experience running `Hangfire.Tags` in production. In my case, `10 retries` with `100 milliseconds delay each` were not enough. It would still occasionally fail with the concurrency error. `50 retries` seems to be enough in my very scenario, but it is not guaranteed, really. 

With that in mind, I'm thinking that the retry count option should be exposed to the consumers so that they can increase it, if the default retry count is not enough. Or we can do retries until the call succeeds. However, it may not be safe, so I'm not confident in having infinite retry number.

**Comment by erwin-faceit** [comment]
Oh wow, I'm so sorry that I've forgotten all about your PR. Thanks for the hard work! I've tried your PR on my machine, and I hardly get any concurrency issues (different hardware).

I do think your PR looks great! I will change some small parts of the ```TagsStorageTransactionRetryPolicy``` class, to make it possible to have no retries, and also make it possible to add a delay between retries (using Thread.Sleep, unfortunately). Also, it will throw the exception now if the amount of retries is used up.

I also like the fact you've implemented a default retry policy. I did rename it do, since it, in fact is not doing nothing ;).

**Comment by erwin-faceit** [comment]
At the moment I'm looking at the integration test that you wrote, and it occurs to me (again) that this issue is not Hangfire.Tags specific. I'm using a `PostgreSqlWriteOnlyTransaction` from [Hangfire.PostgreSQL](https://github.com/frankhommers/Hangfire.PostgreSql) and invoking a method, which fails. 

The commit itself is out of my hands, but every other project that relies on this library and uses methods like AddToSet, AddToList, etc. has the possibility to fail.

I've also compared the PostgreSQL implementation with the [MySQL](https://github.com/arnoldasgudas/Hangfire.MySqlStorage) implementation, and noticed that the MySQL implementation uses ReadCommitted by default. There is a different implementation, especially to prevent deadlocks ([Hangfire.Storage.MySql](https://github.com/MiloszKrajewski/Hangfire.Storage.MySql)).

I'm not a fan of adding multiple implementations, but I do think we should fix this problem where it occurs, which is in Hangfire.PostgreSQL. If you agree, we could prepare a PR for Hangfire.PostgreSQL instead.

**Comment by erwin-faceit** [comment]
Also, did you see [this implementation](https://github.com/ahydrax/Hangfire.PostgreSql)? It uses ReadCommitted, and also uses different queries.

**Comment by Frazi1** [comment]
> If you agree, we could prepare a PR for Hangfire.PostgreSQL instead.

I definitely agree. You have really good thoughts about it.

I will take a better look at all the links you posted a little bit later, when I'm done with work. Also, I can open up an issue in Hangfire.Postgres repo and document our findings there (feel free to do it yourself if you want).

P.S. It may be worth looking at SqlServer implementation as well.

**Comment by Frazi1** [comment]
Hello @erwin-faceit 

I wanted to let you know that I did open an issue in Hangfire.Postgres repository: https://github.com/frankhommers/Hangfire.PostgreSql/issues/191. I appreciate your help working on this case with me.

I do like your idea of switching to `ReadCommitted` isolation level and following the approach other storages take. But I'm not confident making that change in Hangfire.Postgres yet because it can easily lead to regressions. Some research and testing are definitely required here.

If you have some ideas, let's continue our conversation in Hangfire.Postgres repo. I also hope to hear from Hangfire.Postgres maintainers. Myself, I do plan on playing around with Hangfire.Postgres, changing the isolation level to see how it behaves.

**Comment by erwin-faceit** [comment]
I'm going to give you kudos for your excellent issue reports! It contains so much information, that it's a breeze to work with. Let's see where it goes, I'm going to follow that issue, and I'll close this one for now. If something changes, we can reopen it again.
